name: Build LaTeX documents
on:
  push:
    paths:
      - "**.tex"
    tags:
      - "**"

jobs:
  build_pdfs:
    runs-on: ubuntu-latest
    env:
      TZ: "America/New_York"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            academic:
              - 'academic/**.tex'
            industry:
              - 'industry/**.tex'

      - name: Compile CV PDF
        uses: xu-cheng/latex-action@v2
        if: steps.changes.outputs.academic == 'true'
        with:
          root_file: academic/cv.tex

      - name: Compile Resume PDF
        uses: xu-cheng/latex-action@v2
        if: steps.changes.outputs.industry == 'true'
        with:
          root_file: industry/resume.tex
  
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pdfs-${{github.sha}}
          path: |
            *.pdf
          retention-days: 14
         # overwrite: true

  #     - name: Release with asset
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           *.pdf
  #         token: ${{ secrets.TOKEN }}

  open_pr:
    needs: build_pdfs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: nicholasosaka/nosaka.xyz
          path: nosaka.xyz
      - name: Get PDFs from build
        uses: actions/download-artifact@v7
        with:
          name: pdfs-${{github.sha}}
          path: nosaka.xyz/public/

      - name: Verify PDFs
        run: |
          ls -l nosaka.xyz/public/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          path: nosaka.xyz
          add-paths: |
            public/*.pdf
          commit-message: Update Resume/CV PDFs
          committer: Nicholas Osaka <nicholas.osaka@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update Resume/CV PDFs to latest
          branch: cv-update
          delete-branch: true

  create_release:
    if: github.ref_type == 'tag'
    needs: build_pdfs
    runs-on: ubuntu-latest
    steps:

      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1
        with:
          tag-pattern: "*"

      - name: Output Data
        run: |
          echo "tag: ${{ steps.changes.outputs.tag }}"
          echo "changes: ${{ steps.changes.outputs.changes }}"

      - name: Get tex files added or modified
        run: |
          echo "${{ steps.changes.outputs.changes }}" | awk '{print $2}' | xargs git rev-parse > commits.txt
          cat commits.txt
          cat commits.txt | xargs git show --oneline --pretty="" --name-only --diff-filter=AM | sort -u > files_changed.txt
          cat files_changed.txt
          
          if [ -s files_changed.txt ] && grep cv files_changed.txt > /dev/null; then
            echo "Found CV update."
            echo CV_UPDATE=1 >> $GITHUB_ENV
            echo "CV_LATEST=$(cat commits.txt | xargs git show --oneline --pretty="format:%H" --name-only --diff-filter=AM | sed -e ':a' -e 'N' -e '$!ba' -e 's/\([^\n]\)\n\([^\n]\)/\1 \2/g' | grep cv | awk  'NR==1 {print $1}')" >> $GITHUB_ENV
          else
            echo "No CV update found."
            echo CV_UPDATE=0 >> $GITHUB_ENV
          fi

          if [ -s files_changed.txt ] && grep resume files_changed.txt > /dev/null; then
            echo "Found resume update."
            echo RESUME_UPDATE=1 >> $GITHUB_ENV
            echo "RESUME_LATEST=$(cat commits.txt | xargs git show --oneline --pretty="format:%H" --name-only --diff-filter=AM | sed -e ':a' -e 'N' -e '$!ba' -e 's/\([^\n]\)\n\([^\n]\)/\1 \2/g' | grep resume | awk  'NR==1 {print $1}')" >> $GITHUB_ENV
          else
            echo "No resume update found."
            echo RESUME_UPDATE=0 >> $GITHUB_ENV
          fi

      - name: Get commit hashes
        run: |
          echo "RESUME_LATEST: $RESUME_LATEST"
          echo "CV_LATEST: $CV_LATEST"

          if [ "$RESUME_LATEST" = "${{github.sha}}" ]; then
              echo "RESUME_LATEST is the latest commit."
              echo "OTHER_TO_DOWNLOAD=$RESUME_LATEST" >> $GITHUB_ENV
          fi
          if [ "$CV_LATEST" = "${{github.sha}}" ]; then
              echo "CV_LATEST is the latest commit."
              echo "OTHER_TO_DOWNLOAD=$CV_LATEST" >> $GITHUB_ENV
          fi

      - name: Get PDF(s) from older build
        uses: actions/download-artifact@v7
        with:
          name: pdfs-${{env.OTHER_TO_DOWNLOAD}}
          path: .

      - name: Get PDF(s) from current build and overwrite old PDF(s) if needed
        uses: actions/download-artifact@v7
        with:
          name: pdfs-${{github.sha}}
          path: .

      - name: Create CHANGLOG from commits where PDFs were updated
        runs: |
          cat commits.txt | xargs git show -s --date=short --pretty=format:"%ad %s" > ${{github.workspace}}-CHANGELOG.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.pdf
          token: ${{ secrets.TOKEN }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
