name: Build LaTeX document
on:
  push:
    tags:
      - "*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Rename PDF output 
        run: mv main.pdf osaka-cv.pdf
      - name: Release with asset
        uses: softprops/action-gh-release@v1
        with:
          files: osaka-cv.pdf
          token: ${{ secrets.TOKEN }}

