name: Build LaTeX document
on:
  push:
    tags:
      - "*"

jobs:
  build_cv_tex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: osaka-cv.tex
      - name: Release with asset
        uses: softprops/action-gh-release@v1
        with:
          files: osaka-cv.pdf
          token: ${{ secrets.TOKEN }}

