name: Build LaTeX documents
on:
  push:
    paths:
      - "**.tex"

jobs:
  build_pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            academic:
              - 'academic/**.tex'
            industry:
              - 'induustry/**.tex'

      - name: Compile CV PDF
        uses: xu-cheng/latex-action@v2
        if: github.steps.changes.outputs.academic == 'true'
        with:
          root_file: academic/cv.tex

      - name: Compile Resume PDF
        uses: xu-cheng/latex-action@v2
        if: github.steps.changes.outputs.industry == 'true'
        with:
          root_file: industry/resume.tex
  
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: |
            *.pdf
         # overwrite: true

  #     - name: Release with asset
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           *.pdf
  #         token: ${{ secrets.TOKEN }}

  update_web:
    needs: build_pdfs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: nicholasosaka/nosaka.xyz
          path: nosaka.xyz
      - name: Get PDFs from build
        uses: actions/download-artifact@v3
        with:
          name: pdfs
          path: nosaka.xyz/public/

      - name: Verify PDFs
        run: |
          ls -l nosaka.xyz/public/
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v5
  #       with:
  #         token: ${{ secrets.TOKEN }}
  #         path: nosaka.xyz
  #         add-paths: |
  #           public/*.pdf
  #         commit-message: Update Resume/CV PDFs
  #         committer: Nicholas Osaka <nicholas.osaka@gmail.com>
  #         author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
  #         title: Update Resume/CV PDFs to latest
  #         branch: cv-update
  #         delete-branch: true
