name: Build LaTeX document
on:
  push:
    tags:
      - "industry/*-*-*"

jobs:
  build_resume_tex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Rename cv to resume
        run: mv cv.pdf resume.pdf
      - name: Release with asset
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
          token: ${{ secrets.TOKEN }}
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: nicholasosaka/nosaka.xyz
          path: nosaka.xyz
      - name: Prepare Pull Request content
        run: |
          pwd
          ls
          cd nosaka.xyz
          pwd
          ls 
          echo "ls ../"
          ls ../
          cp ../resume.pdf web/public/resume.pdf
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          path: nosaka.xyz
          add-paths: |
            web/public/resume.pdf
          commit-message: Update industry resume
          committer: Nicholas Osaka <nicholas.osaka@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update resume to latest
          branch: resume-update
          delete-branch: true
